import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ChevronDown, ChevronRight, Loader2 } from "lucide-react";
import { toast } from "react-toastify";
import API from "../../api/axios";
import VideoFrame from "../../Components/VideoFrame";

export default function LearnCourse() {
  const { id } = useParams(); const [course, setCourse] = useState(null); const [active, setActive] = useState(null); const [open, setOpen] = useState({});
  useEffect(() => { API.get(`/course/learn/${id}`).then(({ data }) => { setCourse(data.course); setActive(data.course.chapters?.[0]?.lessons?.[0] || null); setOpen({ [data.course.chapters?.[0]?._id]: true }); }).catch((e) => toast.error(e.response?.data?.message || "Could not open course.")); }, [id]);
  if (!course) return <div className="flex h-[65vh] items-center justify-center"><Loader2 className="animate-spin text-orange-500" size={45}/></div>;
  return <section className="space-y-6 text-white"><Link to="/student/courses" className="inline-flex items-center gap-2 text-orange-400"><ArrowLeft size={18}/> My courses</Link><div className="grid gap-6 xl:grid-cols-[1.65fr_.8fr]"><main className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.045]"><div className="aspect-video bg-black"><VideoFrame url={active?.video?.url} title={active?.title} resources={active?.resources || []}/></div><div className="p-6"><p className="text-sm text-orange-300">{course.title}</p><h1 className="mt-2 text-2xl font-bold">{active?.title}</h1><p className="mt-3 text-white/55">{active?.description}</p>{active?.resources?.length > 0 && <p className="mt-4 text-sm text-orange-300">Resources are available above the video.</p>}</div></main><aside className="rounded-3xl border border-white/10 bg-white/[.045] p-4"><h2 className="mb-4 font-semibold">Course content</h2>{course.chapters.map((chapter, index) => <div key={chapter._id} className="mb-2 rounded-2xl bg-black/20"><button onClick={() => setOpen({ ...open, [chapter._id]: !open[chapter._id] })} className="flex w-full items-center gap-2 p-3 text-left"><span className="text-orange-400">{open[chapter._id] ? <ChevronDown size={17}/> : <ChevronRight size={17}/>}</span><span>{index + 1}. {chapter.title}</span></button>{open[chapter._id] && <div className="border-t border-white/10 p-2">{chapter.lessons.map((lesson) => <button key={lesson._id} onClick={() => setActive(lesson)} className={`w-full rounded-xl p-2.5 text-left text-sm ${active?._id === lesson._id ? "bg-orange-500/15 text-orange-200" : "text-white/65"}`}>{lesson.title}{lesson.resources?.length > 0 && <span className="ml-2 text-xs text-orange-300">• {lesson.resources.length} resource</span>}</button>)}</div>}</div>)}</aside></div></section>;
}
