import { useState } from "react";
import { Loader2, Mail, X } from "lucide-react";
import { toast } from "react-toastify";
import API from "../../api/axios";

export default function SendStudentEmailModal({ open, onClose, student }) {
  const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false);
  if (!open || !student) return null;
  const send = async (event) => { event.preventDefault(); try { setSending(true); const { data } = await API.post(`/admin/student/${student._id}/email`, { subject, message }); toast.success(data.message); setSubject(""); setMessage(""); onClose(); } catch (error) { toast.error(error.response?.data?.message || "Could not send email."); } finally { setSending(false); } };
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={send} className="w-full max-w-xl rounded-3xl border border-orange-500/25 bg-[#15110f] p-6 shadow-[0_20px_80px_rgba(0,0,0,.6)]"><div className="flex items-center justify-between"><div><p className="text-sm text-orange-400">STUDENT COMMUNICATION</p><h2 className="mt-1 text-2xl font-bold text-white">Send personal email</h2></div><button type="button" onClick={onClose} className="text-white/55 hover:text-white"><X/></button></div><div className="mt-6 grid gap-4"><label className="text-sm text-white/55">Student name<input readOnly value={student.name} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-white/70"/></label><label className="text-sm text-white/55">Student email<input readOnly value={student.email} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-white/70"/></label><label className="text-sm text-white/55">Subject<input required value={subject} onChange={(e) => setSubject(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 p-3 text-white outline-none focus:border-orange-500" placeholder="Important update from Stack Adda"/></label><label className="text-sm text-white/55">Message<textarea required rows="6" value={message} onChange={(e) => setMessage(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 p-3 text-white outline-none focus:border-orange-500" placeholder="Write your message…"/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-white/15 px-5 py-3 text-white/75">Cancel</button><button disabled={sending} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 font-semibold text-white hover:bg-orange-600 disabled:opacity-60">{sending ? <Loader2 size={18} className="animate-spin"/> : <Mail size={18}/>}Send email</button></div></form></div>;
}
