import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { FilePlus2, Loader2, Trash2, Upload } from "lucide-react";
import { toast } from "react-toastify";
import API from "../../api/axios";

export default function ResourceManager() {
  const { id } = useParams(); const [course, setCourse] = useState(null); const [selected, setSelected] = useState(""); const [form, setForm] = useState({ title: "", url: "", file: null }); const [saving, setSaving] = useState(false);
  const load = async () => { try { const { data } = await API.get(`/course/course/${id}`); setCourse(data.course); } catch (e) { toast.error(e.response?.data?.message || "Could not load resources."); } };
  useEffect(() => { load(); }, [id]);
  const lesson = course?.chapters.flatMap((chapter) => chapter.lessons.map((item) => ({ ...item, chapterId: chapter._id, chapterTitle: chapter.title }))).find((item) => item._id === selected);
  const add = async (event) => { event.preventDefault(); if (!lesson) return toast.error("Select a lesson."); try { setSaving(true); const data = new FormData(); data.append("title", form.title); if (form.file) data.append("resource", form.file); else data.append("url", form.url); await API.post(`/course/course/${id}/chapter/${lesson.chapterId}/lesson/${lesson._id}/resource`, data, { onUploadProgress: () => {} }); toast.success("Resource added."); setForm({ title: "", url: "", file: null }); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not add resource."); } finally { setSaving(false); } };
  const remove = async (resource) => { if (!window.confirm("Delete this resource?")) return; try { await API.delete(`/course/course/${id}/chapter/${lesson.chapterId}/lesson/${lesson._id}/resource/${resource._id}`); toast.success("Resource deleted."); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not delete resource."); } };
  if (!course) return <div className="flex h-[60vh] items-center justify-center"><Loader2 className="animate-spin text-orange-500"/></div>;
  return <section className="mx-auto max-w-5xl space-y-7 text-white"><Link to={`/admin/course/${id}`} className="text-orange-400">← Back to course builder</Link><div><p className="text-orange-400">COURSE MATERIALS</p><h1 className="mt-1 text-3xl font-bold">Resources for {course.title}</h1></div><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={add} className="h-fit rounded-3xl border border-white/10 bg-white/[.045] p-6"><h2 className="flex items-center gap-2 font-semibold"><FilePlus2 className="text-orange-400"/> Add resource</h2><select required value={selected} onChange={(e) => setSelected(e.target.value)} className="mt-5 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-white"><option value="">Choose lesson</option>{course.chapters.flatMap((chapter) => chapter.lessons.map((item) => <option key={item._id} value={item._id}>{chapter.title} — {item.title}</option>))}</select><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Resource title e.g. Chapter notes" className="mt-3 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white"/><input type="url" disabled={Boolean(form.file)} value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} placeholder="External resource URL" className="mt-3 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white disabled:opacity-40"/><label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-white/20 p-3 text-sm text-white/60"><Upload size={17}/>{form.file?.name || "Or upload PDF, DOCX, TXT, ZIP"}<input hidden type="file" accept=".pdf,.doc,.docx,.txt,.zip" onChange={(e) => setForm({ ...form, file: e.target.files[0], url: "" })}/></label><button disabled={saving} className="mt-4 w-full rounded-xl bg-orange-500 py-3 font-medium hover:bg-orange-600 disabled:opacity-60">{saving ? "Adding resource…" : "Add resource"}</button></form><div className="space-y-3">{lesson ? <>{(lesson.resources || []).map((resource) => <div key={resource._id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><a className="min-w-0 flex-1 truncate text-orange-300 hover:underline" href={resource.url} target="_blank" rel="noreferrer">{resource.title}</a><button onClick={() => remove(resource)} className="text-red-400"><Trash2 size={18}/></button></div>)}{!lesson.resources?.length && <p className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-white/45">No resources for this lesson.</p>}</> : <p className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-white/45">Select a lesson to manage its resources.</p>}</div></div></section>;
}
